### PR TITLE
Fix dependency graph after update to zipkin 1.9.2

### PR DESCRIPTION
**Pull request by pavolloffay**

### CODE REVIEW

**Comment by pavolloffay** [comment]
In order to show A->B in dependency graph span has to contain `cs` with endpoint `A` and `sr` with endpoint `B`

**Comment by nicolaferraro** [comment]
Hi @pavolloffay, I didn't see this PR, I've opened another one (#8).
Actually the problem was that I misinterpreted the meaning of the client service mappings, that should reflect the application calling the remote service, not the remote service. I've also removed the internal endpoints. 

Didn't test yours, but it seems asymmetric, while each remote service should be treated the same way.

**Comment by pavolloffay** [comment]
This solves this issue msa-api-gateway-dep-issue 

@nicolaferraro that is perfect :100: . I hope yours work fine.  @rafabene feel free to close this once 
https://github.com/redhat-helloworld-msa/api-gateway/pull/8 is merged.

**Comment by rafabene** [comment]
Yeap! #8 fixed the issue! Thank you guys.

**Pull request closed without merging**
