### PR TITLE
Jaeger tracing spring-boot-camel

### PR DESCRIPTION
**Pull request by pavolloffay**
Do not merge yet!  It depends on camel-opentracing snapshot!

### CODE REVIEW

**Comment by pavolloffay** [comment]
Attaching images with generated traces. Note that service names are broken and trace seems to be broken too.

microservices frontend 2

microservices frontend 1

cc @objectiser

**Comment by objectiser** [comment]
Currently the hystrix config fix results the api-gateway blocking if one (or more) of the services are not available. Investigating possible solutions.

**Comment by pavolloffay** [comment]
All issues has been fixed.

**Comment by objectiser** [comment]
@pavolloffay Tested invoking api-gw via curl, and scaling down aloha to test fallback - all displayed correctly in Jaeger UI.

**Pull request merged**
