### PR TITLE
Fixes #25: use Camel in api-gateway

### PR DESCRIPTION
**Pull request by nicolaferraro**
@rafabene I found the time to complete it and move to camel-zipkin for tracing (so we can easily switch to camel-opentracing in the future). I tested all integrations (zipkin, hystrix, etc).

I'm going to open other PRs for documentation and frontend changes.

### CODE REVIEW

**Comment by rafabene** [comment]
Hi, I couldn't find the /api/health endpoint for health check. Can you clarify that to me? Maybe this file should be also updated: https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/ansible/vars.yml#L61

**Comment by nicolaferraro** [comment]
Hi, it should be ok. I've added the spring-boot actuator module, that exposes automatically a `/health` endpoint (not `/api/health`). Any problem occurring in spring-boot or Camel is signaled internally to the actuator module, resulting in bad health.

**Comment by pavolloffay** [comment]
@nicolaferraro hello! Just for curiosity why did you updated brave version from `4.0.6` to `3.9.1`? 

We have updated zipkin to `1.9.2` and there dependency diagram does not look right.

**Comment by nicolaferraro** [comment]
Hi, I think that 3.9.1 was the version present before I started working, probably I've used 4.0.6 in one intermediate step, then revert.

Anyway, I'm investigating why the behaviour changed. I'll commit a solution or roll back to previous zipkin configuration (without the camel-zipkin module).

**Comment by pavolloffay** [comment]
see https://github.com/redhat-helloworld-msa/api-gateway/pull/7#issuecomment-289493871 I have asked on zipkin gitter about this. I think that is the real issue.

**Pull request merged**
